# -*- coding: utf-8 -*-
"""Nuevo código del pp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J83pjMD6Wv1EgyHvnyUVcYjHlK14teYr
"""

import base64
import random
import os

# --- 1. CONFIGURACIÓN DE PARÁMETROS ---
NUM_PREGUNTAS_TECNICAS = 12
NUM_PREGUNTAS_BLANDAS = 13
PUNTAJE_MINIMO_BLANDAS = 0.75  # 75%

# ---------------- RSA SIMULADO ---------------------
def generar_clave_rsa_simulada():
    return base64.b64encode(os.urandom(16)).decode("utf-8")

def cifrar_rsa_simulado(datos, clave_publica):
    datos_codificados = base64.b64encode(datos.encode("utf-8")).decode("utf-8")
    return f"RSA-CIPHER:{clave_publica[:10]}...{datos_codificados}"

# --- 2. PREGUNTAS DEL CUESTIONARIO ---
PREGUNTAS_TECNICAS = [
    "¿Sabe realizar inventarios físicos y conteos rápidos de material de construcción?",
    "¿Ha utilizado algún software de Punto de Venta (POS) o sistema de facturación electrónica?",
    "¿Sabe leer e interpretar una hoja de ruta o usar GPS para optimizar entregas?",
    "¿Tiene experiencia o conoce el manejo básico de un montacargas o patín hidráulico?",
    "¿Puede identificar y diferenciar los tipos de cemento, varilla y arena comunes en la construcción?",
    "¿Sabe cómo se calcula el volumen o área de un material (ej. m³ de arena, m² de loseta)?",
    "¿Se siente cómodo manejando una terminal bancaria y realizando cobros con tarjeta?",
    "¿Puede verificar y cotejar una orden de compra contra el material físico que se va a cargar?",
    "¿Conoce las normas básicas de seguridad para cargar y descargar materiales pesados?",
    "¿Tiene conocimientos básicos de uso de hojas de cálculo (Excel, Google Sheets) para reportes?",
    "¿Sabe realizar el mantenimiento básico o limpieza de herramientas y equipos de trabajo?",
    "¿Puede calcular rápidamente el cambio para un pago en efectivo?"
]

PREGUNTAS_BLANDAS = [
    "¿Mantiene la calma y es cortés al tratar con un cliente enojado o impaciente?",
    "¿Se adapta fácilmente a los cambios de tareas o prioridades de última hora?",
    "¿Ofrece ayuda a sus compañeros sin que se lo pidan?",
    "¿Es puntual y respeta estrictamente los horarios?",
    "¿Acepta retroalimentación sin ponerse a la defensiva?",
    "¿Se enfoca en soluciones en lugar de culpar a otros?",
    "¿Es proactivo buscando tareas pendientes?",
    "¿Se comunica de manera clara y concisa?",
    "¿Trabaja bien bajo presión?",
    "¿Su honestidad y ética son inquebrantables?",
    "¿Prioriza la seguridad ante todo?",
    "¿Propone mejoras a procesos ineficientes?",
    "¿Se siente cómodo pidiendo al cliente verificar la carga/ticket?"
]

# --- ASIGNACIÓN DE ÁREA ---
def asignar_area(respuestas):
    """
    Recibe lista de S/N del cuestionario técnico y asigna área laboral.
    """

    AREAS = {
        "CARGADOR":       [0, 3, 4, 7, 8],
        "VENTAS/COBRANZA":[1, 6, 11],
        "REPARTIDOR":     [2, 3, 7, 8],
        "LIMPIEZA":       [10],
        "ADMINISTRATIVO": [9]
    }

    conteo = {area: 0 for area in AREAS}

    for area, indices in AREAS.items():
        for idx in indices:
            if respuestas[idx] == "S":
                conteo[area] += 1

    area_final = max(conteo, key=conteo.get)
    return area_final

# --- 3. FUNCIONES PRINCIPALES ---
def pedir_datos_personales():
    datos = {}
    print("---  DATOS PERSONALES ---")
    datos["nombre"] = input("Nombre completo: ").strip()
    datos["edad"] = input("Edad: ").strip()
    datos["sexo"] = input("Sexo (M/F/Otro): ").strip()
    datos["correo"] = input("Correo electrónico (Será cifrado): ").strip()
    datos["telefono"] = input("Número de teléfono (Será cifrado): ").strip()
    return datos

def realizar_cuestionario(preguntas, tipo):
    respuestas = []
    puntaje = 0

    print(f"\n---  HABILIDADES {tipo.upper()} ({len(preguntas)} preguntas) ---")
    for i, pregunta in enumerate(preguntas):
        while True:
            r = input(f"{i+1}. {pregunta} (S/N): ").upper().strip()
            if r in ("S", "N"):
                respuestas.append(r)
                if r == "S":
                    puntaje += 1
                break
            print(" Respuesta no válida. Solo S o N.")
    return puntaje, respuestas

def evaluar_resultados(pt_tecnico, pt_blando):
    porcentaje_tecnico = (pt_tecnico / NUM_PREGUNTAS_TECNICAS) * 100
    porcentaje_blando = (pt_blando / NUM_PREGUNTAS_BLANDAS) * 100
    es_aceptado = porcentaje_blando >= (PUNTAJE_MINIMO_BLANDAS * 100)
    return es_aceptado, porcentaje_tecnico, porcentaje_blando

# --- 4. EJECUCIÓN PRINCIPAL ---
def iniciar_proceso_seleccion():
    print("=====================================================")
    print("     PROCESO DE SELECCIÓN - BRICOS")
    print("=====================================================")

    datos_usuario = pedir_datos_personales()

    # Cifrado RSA simulado
    clave_publica = generar_clave_rsa_simulada()
    datos_cifrados = cifrar_rsa_simulado(
        f"Email:{datos_usuario['correo']}|Tel:{datos_usuario['telefono']}",
        clave_publica
    )
    print("\nDatos de contacto CIFRADOS correctamente.")

    # Cuestionarios
    pt_tecnico, respuestas_tecnicas = realizar_cuestionario(PREGUNTAS_TECNICAS, "TÉCNICAS")
    pt_blando, _ = realizar_cuestionario(PREGUNTAS_BLANDAS, "BLANDAS")

    # Evaluación
    es_aceptado, pct_tecnico, pct_blando = evaluar_resultados(pt_tecnico, pt_blando)

    # Asignación de área
    area = asignar_area(respuestas_tecnicas)

    # Resultados
    print("\n=====================================================")
    print("              RESULTADO FINAL")
    print("=====================================================")
    print(f"Habilidades Técnicas: {pt_tecnico}/{NUM_PREGUNTAS_TECNICAS} ({pct_tecnico:.2f}%)")
    print(f"Habilidades Blandas:  {pt_blando}/{NUM_PREGUNTAS_BLANDAS} ({pct_blando:.2f}%)")
    print("-----------------------------------------------------")

    if es_aceptado:
        print(" ESTADO FINAL: ¡ACEPTADO! (Cumple el 75% en habilidades blandas)")
    else:
        print(" ESTADO FINAL: NO ACEPTADO (No cumple el 75% en habilidades blandas)")

    print(f"\nÁrea recomendada según habilidades técnicas: {area}")

    print("\n=====================================================")
    print("--- REGISTRO GUARDADO ---")
    print(f"Nombre: {datos_usuario['nombre']} | Edad: {datos_usuario['edad']}")
    print(f"DATOS CIFRADOS: {datos_cifrados}")

# Ejecutar
if __name__ == "__main__":
    iniciar_proceso_seleccion()